update to Django 5.2
mongodb/django-mongodb-backend pull request #199
Opened 2024-12-14 20:24 UTC by timgraham

Django 5.2 will be released April 2025.

This is to check compatibility in the meantime.

2025-04-18 03:28 UTC, WaVEV commented on django_mongodb_backend/expressions.py
> +def expression_list(self, compiler, connection):
to be consistent with JSONArray.as_mql. We should chose to encapsulate the process_lhs or just assign the function as it is

2025-04-23 17:33 UTC, Jibola commented on django_mongodb_backend/__init__.py
> +__version__ = "5.2.0a0"
```suggestion
__version__ = "5.2.0b0.dev"
```

2025-04-23 20:19 UTC, Jibola requested changes
Things overall look good. Left some questions to get clarity. Once those receive response we should be good to go!

2025-04-23 20:19 UTC, Jibola commented on django_mongodb_backend/compiler.py
> +        return tuple(selected) + tuple(map(project_field, related_columns))
I'm trying to understand this new functionality:
From what I'm understanding, it checks which columns are SELECTED on column registry? 
It looks like this is new functionality to only render selected columns and annotations?

Also, is this new feature support or has this behavior just been moved from elsewhere.

2025-04-23 20:19 UTC, Jibola commented on django_mongodb_backend/compiler.py
> +                    compiler_.query = compiler_.query.clone()
why are we cloning the compiler_ back into itself?

2025-04-23 20:19 UTC, Jibola commented on docs/source/intro/configure.rst
> +    $ django-admin startproject mysite --template https://github.com/mongodb-labs/django-mongodb-project/archive/refs/heads/5.2.x.zip
@aclark4life can you make the new ref for django-mongodb-project?

2025-04-23 20:19 UTC, Jibola commented on django_mongodb_backend/operations.py
> -
Why is this no longer relevant?

2025-04-23 20:19 UTC, Jibola commented on django_mongodb_backend/lookups.py
> -        raise NotImplementedError("MultiColSource is not supported.")
Is this full feature support a consequence of a feature enhancement, or is it due to a change required from the 5.2 upgrade? If it's the former, could it be split into a different PR?

2025-04-23 20:19 UTC, Jibola commented on django_mongodb_backend/fields/array.py
> -                return [self.base_field.get_db_prep_save(i, connection) for i in value]
🚀

2025-04-23 21:59 UTC, aclark4life commented on docs/source/intro/configure.rst
> +    $ django-admin startproject mysite --template https://github.com/mongodb-labs/django-mongodb-project/archive/refs/heads/5.2.x.zip
Done!

2025-04-23 22:08 UTC, aclark4life commented on django_mongodb_backend/compiler.py
> +                    compiler_.query = compiler_.query.clone()
"If this query contains related items and the compiler's query does not, assign the related items to the compiler's query…" Right, that is confusing to me too. Maybe that should be `compiler_.query = selected.clone()`?

2025-04-23 22:50 UTC, aclark4life commented on django_mongodb_backend/operations.py
> -
Possibly a [remnant of mongoengine](https://github.com/mongodb/django-mongodb-backend/pull/2#discussion_r1590188184).

2025-04-23 23:00 UTC, aclark4life commented on django_mongodb_backend/lookups.py
> -        raise NotImplementedError("MultiColSource is not supported.")
I'm going to go with [the latter](https://github.com/django/django/pull/18404) and also [the import can be removed](https://github.com/mongodb/django-mongodb-backend/blob/43f477cc2e1a0981e53bc2a60ee0e049939c716f/django_mongodb_backend/lookups.py#L2).

2025-04-23 23:01 UTC, aclark4life commented on django_mongodb_backend/compiler.py
> +        return tuple(selected) + tuple(map(project_field, related_columns))
Possibly related to https://github.com/django/django/pull/18404

2025-04-24 01:19 UTC, timgraham commented on django_mongodb_backend/operations.py
> -
I put details about some of the changes in the commit messages. In this case: "Remove special-casing of DecimalField calling adapt_decimalfield_value() obsoleted by https://github.com/django/django/commit/1860a1afc9ac20750f932e8e0a94b32d096f2848"

2025-04-24 01:23 UTC, timgraham commented on django_mongodb_backend/lookups.py
> -        raise NotImplementedError("MultiColSource is not supported.")
Essentially, `MultiColSource` was refactored to `ColPairs`. It's still unsupported but the error is raised differently.

2025-04-24 01:25 UTC, timgraham commented on django_mongodb_backend/compiler.py
> +        return tuple(selected) + tuple(map(project_field, related_columns))
Look at the second commit: "Fix columns order in aggregation queries". There is a link to the Django commit that necessitates this change. Emanuel did the work, so if you have any further questions, I'll defer to him rather than dig into it myself.

2025-04-24 01:53 UTC, timgraham commented on django_mongodb_backend/compiler.py
> +                    compiler_.query = compiler_.query.clone()
The same line is present a few lines below (496). It's important not to mutate a query in case the queryset is reused: https://github.com/django/django/commit/14d026cccb144c6877294ba4cd4e03ebf0842498.

2025-04-24 01:54 UTC, WaVEV commented on django_mongodb_backend/compiler.py
> +        return tuple(selected) + tuple(map(project_field, related_columns))
The issue here was about reordering some `selected` columns (the part in SELECT col1, col2, ...). These coloumns are reused multiple times throughout the query (in SELECT, GROUP BY, HAVING, and maybe another one I don’t fully remember). I tried a few alternatives, like using this structure and renaming the fields, but I ran into problems with nested queries and GROUP BY. So I ended up standardizing the data coming from ´self.query.selected´ and ´self.query.select´. That way, no matter where the selection columns come from, I keep them consistent (to avoid breaking the rest of the flow, except for the UNION part). I worked on that months ago (December, I think). If you need more info, I can re-review my changes and give you the full details.

2025-04-24 01:56 UTC, WaVEV commented on django_mongodb_backend/compiler.py
> +                    compiler_.query = compiler_.query.clone()
Yes, the object is being referenced in many places. Cloning and set values won't affect other functionalities.

2025-04-24 17:50 UTC, Jibola approved these changes

2025-04-24 18:27 UTC, merged